# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
             - { name: 'twig.extension' }

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    app.picture_handler:
        class:  AppBundle\Service\PictureHandler
        arguments: [ "%previews_dir%", "%pictures_dir%" ]

    app.message_manager:
        class:  AppBundle\Service\MessageManager
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage", "@app.picture_handler" ]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
